### ISSUE TITLE
Asking for help

### ISSUE THREAD

**Issue by rukundo-joe** [Tony133/laravel-api-rest#30]
Would you kindly help me with how to test this API in POSTMAN?
Thank you!

**Comment by Tony133** [comment]
Hi @rukundo-joe,
 
In this example I used terminal curl commands to try and test the API, in fact I put the commands in the Readme, however if you use postman you should do it this way (see screenshot):

Example of an call GET:
<img width="899" alt="screenshot-get-books" src="https://user-images.githubusercontent.com/11542387/192137148-ec4de07b-35e0-4049-98b9-3a20152a6aa9.png">


Example of an call POST:

<img width="899" alt="screenshot-post-book" src="https://user-images.githubusercontent.com/11542387/192137247-7c1d0068-cc4e-49c7-bf81-2ba2b02ccc0e.png">

Remember, however, that first you must generate the basic authentication token via this page, based on the username and password entered in your local database (see screenshot):

<img width="1242" alt="sceenshot-basic-auth" src="https://user-images.githubusercontent.com/11542387/192137443-99aced29-0489-4a6b-9e00-f0d2a214b1ee.png">


alternatively if you want to try it without authentication just remove the basic auth middleware or comment it out, as follows:

```php
//Route::middleware('auth.basic')->group(function () {
    Route::apiResource('books', BooksController::class);
//});
```

I hope I was helpful
